### ISSUE TITLE
test log

### ISSUE THREAD

**Issue by rusefillc** [ElDominio/ParalelaHardware#11]
* it takes firmware via st-link
* with https://rusefi.com/build_server/rusefi_bundle_f407-discovery.zip it's recognized as USB device!

**Comment by rusefillc** [comment]
@ElDominio any plans to try on a real vehicle?

**Comment by ElDominio** [comment]
Yes, will connect to integra

**Comment by ElDominio** [comment]
Now in use in multiple real world vehicles
