### ISSUE TITLE
PC14 does not work, all other outputs do

### ISSUE THREAD

**Issue by ElDominio** [ElDominio/ParalelaHardware#12]
As stated, PC14 seems to do nothing. Is this pin different on APM32?

**Comment by rusefillc** [comment]
"google PC14 stm32" to see if that's one of the special magic pins

looks like it's a pin for low speed oscillator?

![image](https://github.com/ElDominio/ParalelaHardware/assets/48498823/bb2715b4-68e0-46f1-9b9f-2587a8bd4096)

This indicates that custom binary would be needed which is major effort. Would it be possible to adjust hardware and use a less magical stm32 pin?

**Comment by ElDominio** [comment]
Changed pin
