### ISSUE TITLE
only Some APM32 Paralelas report "Device Descriptor Request Failed" on USB, processor seems alive?

### ISSUE THREAD

**Issue by ElDominio** [ElDominio/ParalelaHardware#13]
Some Paralelas after flashing f407-discovery seem to have USB comms die, but still talk fine with STLink, and flash leds as if everything is ok. Satanic possesion? Probably due to Geehy not being STM and incompatibilities from this

**Comment by rusefillc** [comment]
https://github.com/ElDominio/ParalelaHardware/blob/main/V2Fix/Schematic.pdf

**Comment by ElDominio** [comment]
Most of them flash fine, connect to tunerstudio, and after you disconnect and reconnect they never come back to life through usb, even though processor seems to be alive and well

**Comment by rusefillc** [comment]
@ElDominio what oscillator frequency is mounter? 8mhz? 12mhz? else?

![eclipse_k36vJNm0kG](https://github.com/ElDominio/ParalelaHardware/assets/48498823/9a70ac3c-9642-4376-9210-9a07df54350a)

**Comment by rusefillc** [comment]
```"8 MHz"	"X1"	"OSC-SMD_L5.0-W3.2"	"1"	"NX5032GA-8MHZ(STD-CSK-7)"	"Nihon Dempa Kogyo"```

**Comment by ElDominio** [comment]
Where is that? in STM32cube? Or in Device Manager? I don't even know what a "mounter" is

**Comment by rusefillc** [comment]
> Where is that? in STM32cube? Or in Device Manager? I don't even know what a "mounter" is

that's eclipse debugging session

**Comment by ElDominio** [comment]
> Most of them flash fine, connect to tunerstudio, and after you disconnect and reconnect they never come back to life through usb, even though processor seems to be alive and well

Just quoting this because of oddness.
USB comms dies, but everything else is still alive, you can flash firmware as many times as you want but it will still be broken

**Comment by ElDominio** [comment]
@rusefillc not due to processor, same happens on OG STM32 boards. Still alive through DFU

**Comment by ElDominio** [comment]
weirder: they started talking through USB again? with no intervention from my part?

**Comment by rusefillc** [comment]
smells like firmware issue

**Comment by ElDominio** [comment]
Another fun fact:

I got another batch of STM32 Paralelas, have only tested 3 but I have loaded firmware+tune and they all seem alive and well, even with multiple USB connect/disconnects. This is pointing more to a specific hardware+firmware issue concerning APM32. Will have more tests coming in the coming weeks.

@rusefillc  you need 3 STM, and you will ship 1x APM + 1 STM Paralela to Ukraine correct?

**Comment by rusefillc** [comment]
@ElDominio I am mostly interested in BROKEN stm32

please do NOT ship any stm32 of the "good" batch

**Comment by ElDominio** [comment]
At the current time, ALL STM32 Paralelas are working fine. Two had a hiccup yesterday but seem to be back to life with no further errors. Next one that locks up I will put in a box for @rusefillc

**Comment by ElDominio** [comment]
This seems to be very APM-specific. Up until now _ALL_ STM32's have not suffered this for more than one or two restarts, after which it does not come back.

**Comment by ElDominio** [comment]
This is due to using APM32 chips. Zero STM chips have had this issue. If not useful, will close

**Comment by ElDominio** [comment]
Not useful, will close
