### ISSUE TITLE
any specs into readme?

### ISSUE THREAD

**Issue by rusefillc** [ElDominio/ParalelaHardware#2]
does it have USB?
(edited) https://github.com/ElDominio/ParalelaHardware/issues/3
how many injector outputs?

**Comment by ElDominio** [comment]
1) It has USBC
2) God knows
3) 4

**Comment by rusefillc** [comment]
@ElDominio that has to go into https://github.com/ElDominio/ParalelaHardware/blob/main/README.txt?

**Comment by ElDominio** [comment]
1519b3a
