### ISSUE TITLE
arm chip should be powered by USB

### ISSUE THREAD

**Issue by rusefillc** [ElDominio/ParalelaHardware#6]
if you hook USB you should have 3.3 on the chip and happy chip right?

**Comment by ElDominio** [comment]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/5685108/229364406-17b38ad7-d41f-45ba-b312-b279bf62d803.png">


Adding a solder bridge here produces a chip that is happy to wake on USB connection

**Comment by ElDominio** [comment]
Fixed by b19c86d
